apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: OpenShift Optional
    containerImage: ""
    createdAt: ""
    description: Node Maintenance Operator for cordoning and draining nodes.
    repository: https://github.com/medik8s/node-maintenance-operator
    support: Medik8s
  name: node-maintenance-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeMaintenance is the Schema for the nodemaintenances API
      displayName: Node Maintenance
      kind: NodeMaintenance
      name: nodemaintenances.nodemaintenance.medik8s.io
      resources:
      - kind: NodeMaintenance
        name: nodemaintenances
        version: v1beta1
      specDescriptors:
      - description: Node name to apply maintanance on/off
        displayName: Node Name
        path: nodeName
      - description: Reason for maintanance
        displayName: Reason
        path: reason
      statusDescriptors:
      - description: Consecutive number of errors upon obtaining a lease
        displayName: Error On Lease Count
        path: errorOnLeaseCount
      - description: EvictionPods is the total number of pods up for eviction from
          the start
        displayName: Eviction Pods
        path: evictionPods
      - description: LastError represents the latest error if any in the latest reconciliation
        displayName: Last Error
        path: lastError
      - description: PendingPods is a list of pending pods for eviction
        displayName: Pending Pods
        path: pendingPods
      - description: Phase is the represtation of the maintenance progress (Running,Succeeded,Failed)
        displayName: Phase
        path: phase
      - description: TotalPods is the total number of all pods on the node from the
          start
        displayName: Total Pods
        path: totalpods
      version: v1beta1
  description: |
    Node Maintenance Operator (NMO)

    This operator will keep nodes cordoned and drained while a matching NodeMaintenance (nm) custom resource exists.
    This is useful when investigating problems with a machine, or performing an operation on the underlying machine that might result in node failure.

    This is a standalone version of NMO. In case OpenShift Virtualization v4.10.z or less is installed in your cluster, then it has an old NMO.
    Please update OpenShift Virtualization version, and use this newer NMO.
  displayName: Node Maintenance Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - medik8s
  - Node-maintenance
  - nmo
  links:
  - name: Node Maintenance Operator
    url: https://medik8s.io
  - name: Source Code
    url: https://github.com/medik8s/node-maintenance-operator
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: beta
  minKubeVersion: 1.23.0
  provider:
    name: Medik8s
    url: https://github.com/medik8s
  version: 0.0.0
